"""empty message

Revision ID: 31537778156b
Revises: abf3f200692a
Create Date: 2020-04-17 15:15:18.882747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31537778156b'
down_revision = 'abf3f200692a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
